buildenv: check/reduce storage space usage

diff --git a/bin/buildenv b/bin/buildenv
--- a/bin/buildenv
+++ b/bin/buildenv
@@ -1,13 +1,15 @@
 #!/bin/bash -e
 
-while /bin/true; do
-  FREESPACE=$(($(stat -f --format="%a*%S" .)))
-  if [[ $FREESPACE -gt 10737418240 ]]; then # 10G
-     break
-  fi
-  echo "ERROR: Not enough free space to launch build: ${FREESPACE} ..." >&2
-  sleep 300
-done
+if [[ -n "${BUILD_INITIALIZE}" || -n "${BUILD_FINALIZE}" ]]; then
+  while /bin/true; do
+    FREESPACE=$(($(stat -f --format="%a*%S" .)))
+    if [[ $FREESPACE -gt 10737418240 ]]; then # 10G
+       break
+    fi
+    echo "ERROR: Not enough free space to launch build: ${FREESPACE} ..." >&2
+    sleep 300
+  done
+fi
 
 if [[ -n "${BUILD_INIT_CI}" || "$1 $2" == "ci init" ]]; then
   [ -z "${BUILD_CI_URL}" ] && BUILD_CI_URL=$(cd src; git ls-remote --get-url origin | sed -r 's/(.git)?$/-ci\1/g')
@@ -55,10 +57,15 @@ if [ -n "${BUILD_FINALIZE}" ]; then
   if [ -n "${BUILD_SRC_OPENCV_EXTRA}" ]; then (set -e; cd $BUILD_SRC_OPENCV_EXTRA; echo "Extra:"; git status) fi
   opencv_worker_container_dump_diff
   if [ ! -n "${BUILD_PRECOMMIT}" ]; then
+    echo "=== Clean 'build' directory ..."
     (cd build;
       make clean >/dev/null 2>&1 || true
       ninja clean >/dev/null 2>&1 || true
     )
+    if [ -d install ]; then
+      echo "=== Clean 'install' directory ..."
+      rm -rf ./install
+    fi
   fi
   exit $?
 fi
